offers businesses the ability to run applications on the public cloud. 
An EC2 instance is simply a virtual server in Amazon Web Services terminology

An AMI is a template that contains the software configuration (operating system, application server, and applications) required to launch your instance.
Amazon linux
Windows
Ubuntu 
Redhat

Decide on the Instance tye:   computing, memory and storage needs
t2.nano,t2.micro,small,medium,large
t2.2xlarge

